local colors = {
  -- Polar Night (Backgrounds)
  nord0 = '#2E3440',
  nord1 = '#3B4252',
  nord2 = '#434C5E',
  nord3 = '#4C566A',
  -- Snow Storm (Foregrounds)
  nord4 = '#D8DEE9',
  nord5 = '#E5E9F0',
  nord6 = '#ECEFF4',
  -- Frost (Blues/Cyans)
  nord7 = '#8FBCBB',
  nord8 = '#88C0D0',
  nord9 = '#81A1C1',
  nord10 = '#5E81AC',
  -- Aurora (Accents)
  nord11 = '#BF616A', -- Red
  nord12 = '#D08770', -- Orange
  nord13 = '#EBCB8B', -- Yellow
  nord14 = '#A3BE8C', -- Green
  nord15 = '#B48EAD', -- Purple
}

local function setcolor()
  local groups = {
    -- Base groups
    Normal = { fg = colors.nord4, bg = colors.nord0 },
    NormalFloat = { fg = colors.nord4, bg = colors.nord1 },
    FloatWin = { fg = colors.nord4 },
    FloatBorder = { fg = colors.nord8, bg = colors.nord1 },
    NormalNC = { fg = colors.nord4, bg = colors.nord0 },
    CursorLine = { bg = colors.nord1 },
    CursorColumn = { link = 'CursorLine' },
    CursorWord = { underline = true },
    TabLineTop = { fg = colors.nord0, bg = colors.nord0, bold = true },
    TabLineSel = { fg = colors.nord8, bg = colors.nord2, bold = true },
    TabLine = { fg = colors.nord3, bg = colors.nord1, bold = true },
    TabLineFill = { bg = colors.nord0 },
    MatchParen = { fg = colors.nord8, bg = colors.nord3, bold = true },
    ColorColumn = { bg = colors.nord1 },
    Conceal = { fg = colors.nord3 },
    CursorLineNr = { fg = colors.nord4, bg = colors.nord1, bold = true },
    NonText = { fg = colors.nord2 },
    SpecialKey = { fg = colors.nord3 },
    Visual = { bg = colors.nord2 },
    VisualNOS = { link = 'Visual' },
    Search = { fg = colors.nord0, bg = colors.nord8 },
    IncSearch = { fg = colors.nord0, bg = colors.nord13, bold = true },
    CurSearch = { link = 'IncSearch' },
    QuickFixLine = { fg = colors.nord8, bold = true },
    Underlined = { underline = true },
    StatusLine = { fg = colors.nord4, bg = colors.nord0 },
    StatusLineNC = { fg = colors.nord3, bg = colors.nord0 },
    WinBar = { fg = colors.nord4, bg = colors.nord0 },
    WinBarNC = { fg = colors.nord3, bg = colors.nord0 },
    WinSeparator = { fg = colors.nord2, bg = colors.nord0 },
    WildMenu = { fg = colors.nord0, bg = colors.nord8 },
    Directory = { fg = colors.nord8 },
    Title = { fg = colors.nord8, bold = true },
    ErrorMsg = { fg = colors.nord11, bold = true },
    MoreMsg = { fg = colors.nord14 },
    ModeMsg = { fg = colors.nord4, bold = true },
    Question = { fg = colors.nord14 },
    WarningMsg = { fg = colors.nord13, bold = true },
    LineNr = { fg = colors.nord3 },
    SignColumn = { fg = colors.nord3, bg = colors.nord0 },
    Folded = { fg = colors.nord3, bg = colors.nord1 },
    FoldColumn = { fg = colors.nord3, bg = colors.nord0 },
    Cursor = { fg = colors.nord0, bg = colors.nord4 },
    vCursor = { link = 'Cursor' },
    iCursor = { link = 'Cursor' },
    lCursor = { link = 'Cursor' },
    Special = { fg = colors.nord12 },
    Comment = { fg = colors.nord3, italic = true },
    Error = { fg = colors.nord11, bold = true },
    Done = { fg = colors.nord14, bold = true, italic = true },
    Statement = { fg = colors.nord9 },
    Conditional = { fg = colors.nord9 },
    Repeat = { fg = colors.nord9 },
    Label = { fg = colors.nord9 },
    Exception = { fg = colors.nord11 },
    Operator = { fg = colors.nord9 },
    Keyword = { fg = colors.nord9 },
    Identifier = { fg = colors.nord4 },
    Function = { fg = colors.nord8 },
    PreProc = { fg = colors.nord9 },
    Include = { fg = colors.nord9 },
    Define = { fg = colors.nord9 },
    Macro = { fg = colors.nord9 },
    PreCondit = { fg = colors.nord9 },
    Constant = { fg = colors.nord4 },
    Character = { fg = colors.nord14 },
    String = { fg = colors.nord14 },
    Boolean = { fg = colors.nord9 },
    Number = { fg = colors.nord15 },
    Float = { fg = colors.nord15 },
    Type = { fg = colors.nord7 },
    StorageClass = { fg = colors.nord9 },
    Structure = { fg = colors.nord7 },
    Typedef = { fg = colors.nord7 },
    DiffDelete = { fg = colors.nord11, bg = colors.nord1 },
    DiffAdd = { fg = colors.nord14, bg = colors.nord1 },
    DiffChange = { fg = colors.nord13, bg = colors.nord1 },
    DiffText = { fg = colors.nord13, bg = colors.nord2, bold = true },
    SpellCap = { sp = colors.nord13, undercurl = true },
    SpellBad = { sp = colors.nord11, undercurl = true },
    SpellLocal = { sp = colors.nord14, undercurl = true },
    SpellRare = { sp = colors.nord15, undercurl = true },
    Whitespace = { fg = colors.nord2 },
    Delimiter = { fg = colors.nord4 },

    SnippetTabstop = {},
    SnippetTabstopActive = {},

    -- LSP Diagnostic
    DiagnosticError = { fg = colors.nord11 },
    DiagnosticSignError = { fg = colors.nord11 },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.nord11 },
    DiagnosticWarn = { fg = colors.nord13 },
    DiagnosticSignWarn = { fg = colors.nord13 },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.nord13 },
    DiagnosticInfo = { fg = colors.nord8 },
    DiagnosticSignInfo = { fg = colors.nord8 },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.nord8 },
    DiagnosticHint = { fg = colors.nord7 },
    DiagnosticSignHint = { fg = colors.nord7 },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.nord7 },
    DiagnosticFloatingError = { fg = colors.nord11 },
    DiagnosticFloatingWarn = { fg = colors.nord13 },
    DiagnosticFloatingInfo = { fg = colors.nord8 },
    DiagnosticFloatingHint = { fg = colors.nord7 },
    DiagnosticVirtualTextError = { fg = colors.nord11, bg = 'NONE', italic = true },
    DiagnosticVirtualTextWarn = { fg = colors.nord13, bg = 'NONE', italic = true },
    DiagnosticVirtualTextInfo = { fg = colors.nord8, bg = 'NONE', italic = true },
    DiagnosticVirtualTextHint = { fg = colors.nord7, bg = 'NONE', italic = true },
    LspReferenceRead = { bg = colors.nord2 },
    LspReferenceText = { bg = colors.nord2 },
    LspReferenceWrite = { bg = colors.nord2, bold = true },
    LspCodeLens = { fg = colors.nord3, italic = true },
    LspSignatureActiveParameter = { fg = colors.nord13, bold = true },

    -- gitcommit
    gitcommitSelectedFile = { fg = colors.nord14 },
    gitcommitDiscardedFile = { fg = colors.nord11 },

    -- gitsigns.nvim
    GitSignsAdd = { fg = colors.nord14 },
    GitSignsChange = { fg = colors.nord13 },
    GitSignsDelete = { fg = colors.nord11 },
    GitSignsAddLn = { fg = colors.nord14 },
    GitSignsChangeLn = { fg = colors.nord13 },
    GitSignsDeleteLn = { fg = colors.nord11 },

    -- diff
    diffAdded = { fg = colors.nord14 },
    diffRemoved = { fg = colors.nord11 },
    diffChanged = { fg = colors.nord13 },
    diffFile = { fg = colors.nord8 },
    diffNewFile = { fg = colors.nord14 },
    diffOldFile = { fg = colors.nord11 },
    diffLine = { fg = colors.nord8 },
    diffIndexLine = { link = 'diffChanged' },

    -- lspsaga.nvim
    LspSagaCodeActionTitle = { link = 'Title' },
    LspSagaCodeActionBorder = { fg = colors.nord4 },
    LspSagaCodeActionContent = { fg = colors.nord14, bold = true },
    LspSagaLspFinderBorder = { fg = colors.nord4 },
    LspSagaAutoPreview = { fg = colors.nord12 },
    TargetWord = { fg = colors.nord8, bold = true },
    FinderSeparator = { fg = colors.nord9 },
    LspSagaDefPreviewBorder = { fg = colors.nord8 },
    LspSagaHoverBorder = { fg = colors.nord12 },
    LspSagaRenameBorder = { fg = colors.nord8 },
    LspSagaDiagnosticSource = { fg = colors.nord12 },
    LspSagaDiagnosticBorder = { fg = colors.nord15 },
    LspSagaDiagnosticHeader = { fg = colors.nord14 },
    LspSagaSignatureHelpBorder = { fg = colors.nord14 },
    SagaShadow = { fg = colors.nord0 },

    -- Indent
    IndentLine = { fg = colors.nord3 },
    IndentLineCurrent = { fg = colors.nord8 },
    -- StatusLine
    StatusLineMode = { fg = colors.nord4 },
    StatusLineFileInfo = { fg = colors.nord4 },
    StatusLineReadOnly = { fg = colors.nord11 },
    StatusLineBranch = { fg = colors.nord15 },
    StatusLineLsp = { fg = colors.nord3 },
    StatusLineFilesize = { fg = colors.nord3 },
    StatusLineFileType = { fg = colors.nord3 },
    StatusLineEncoding = { fg = colors.nord3 },
    StatlsLineLnum = { fg = colors.nord4 },

    -- pmenu
    Pmenu = { fg = colors.nord4, bg = colors.nord2 },
    PmenuSel = { fg = colors.nord0, bg = colors.nord8, bold = true },
    PmenuSbar = { bg = colors.nord2 },
    PmenuThumb = { bg = colors.nord3 },
    PmenuKind = { fg = colors.nord15, bg = colors.nord2 },
    PmenuKindSel = { fg = colors.nord0, bg = colors.nord8, bold = true },
    PmenuExtra = { fg = colors.nord4, bg = colors.nord2 },
    PmenuExtraSel = { fg = colors.nord0, bg = colors.nord8, bold = true },

    -- cmp
    Cmp = { fg = colors.nord4 },
    CmpBorder = { fg = colors.nord8 },
    BlinkCmpMenu = { link = 'Cmp' },
    BlinkCmpMenuBorder = { link = 'CmpBorder' },
    BlinkCmpDoc = { link = 'Cmp' },
    BlinkCmpDocBorder = { link = 'CmpBorder' },
    BlinkCmpLabel = { link = 'Cmp' },
    BlinkCmpLabelMatch = { fg = colors.nord8, bold = true },
    BlinkCmpKind = { link = 'Cmp' },

    -- nvim-treesitter
    ['@comment'] = { link = 'Comment' },
    ['@comment.documentation'] = { fg = colors.nord3, italic = true },
    ['@comment.note'] = { fg = colors.nord0, bg = colors.nord8, bold = true, italic = true },
    ['@comment.todo'] = { fg = colors.nord0, bg = colors.nord13, bold = true, italic = true },
    ['@comment.error'] = { link = 'Error' },
    ['@none'] = { bg = 'NONE', fg = 'NONE' },
    ['@preproc'] = { link = 'PreProc' },
    ['@define'] = { link = 'Define' },
    ['@operator'] = { link = 'Operator' },
    ['@punctuation.delimiter'] = { fg = colors.nord4 },
    ['@punctuation.bracket'] = { fg = colors.nord4 },
    ['@punctuation.special'] = { fg = colors.nord9 },
    ['@string'] = { link = 'String' },
    ['@string.regex'] = { fg = colors.nord12 },
    ['@string.escape'] = { fg = colors.nord12 },
    ['@string.special'] = { fg = colors.nord12 },
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@boolean'] = { link = 'Boolean' },
    ['@number'] = { link = 'Number' },
    ['@float'] = { link = 'Float' },
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { fg = colors.nord8, italic = true },
    ['@function.call'] = { link = 'Function' },
    ['@function.macro'] = { fg = colors.nord8 },
    ['@method'] = { fg = colors.nord8 },
    ['@method.call'] = { link = 'Function' },
    ['@constructor'] = { fg = colors.nord7 },
    ['@parameter'] = { fg = colors.nord4 },
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.conditional'] = { fg = colors.nord9 },
    ['@keyword.debug'] = { link = 'Debug' },
    ['@keyword.directive'] = { link = 'PreProc' },
    ['@keyword.directive.define'] = { link = 'Define' },
    ['@keyword.exception'] = { fg = colors.nord11 },
    ['@keyword.function'] = { fg = colors.nord9 },
    ['@keyword.import'] = { fg = colors.nord9 },
    ['@keyword.operator'] = { fg = colors.nord9 },
    ['@keyword.repeat'] = { fg = colors.nord9 },
    ['@keyword.return'] = { fg = colors.nord9 },
    ['@keyword.storage'] = { link = 'StorageClass' },
    ['@conditional'] = { link = 'Conditional' },
    ['@repeat'] = { link = 'Repeat' },
    ['@debug'] = { link = 'Debug' },
    ['@label'] = { fg = colors.nord9 },
    ['@include'] = { link = 'Include' },
    ['@exception'] = { link = 'Exception' },
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = { fg = colors.nord9 },
    ['@type.definition'] = { link = 'Typedef' },
    ['@type.qualifier'] = { fg = colors.nord9 },
    ['@storageclass'] = { link = 'StorageClass' },
    ['@attribute'] = { fg = colors.nord12 },
    ['@field'] = { link = 'Identifier' },
    ['@property'] = { link = 'Identifier' },
    ['@variable'] = { fg = colors.nord4 },
    ['@variable.builtin'] = { fg = colors.nord9, italic = true },
    ['@variable.member'] = { fg = colors.nord4 },
    ['@constant'] = { fg = colors.nord4 },
    ['@constant.builtin'] = { fg = colors.nord9 },
    ['@constant.macro'] = { fg = colors.nord9 },
    ['@namespace'] = { fg = colors.nord4 },
    ['@symbol'] = { link = 'Identifier' },
    ['@text'] = { fg = colors.nord4 },
    ['@text.strong'] = { bold = true },
    ['@text.emphasis'] = { italic = true },
    ['@text.underline'] = { underline = true },
    ['@text.strike'] = { strikethrough = true },
    ['@text.title'] = { link = 'Title' },
    ['@text.literal'] = { link = 'String' },
    ['@text.uri'] = { link = 'Underlined' },
    ['@text.math'] = { link = 'Special' },
    ['@text.environment'] = { link = 'Macro' },
    ['@text.environment.name'] = { link = 'Type' },
    ['@text.reference'] = { link = 'Constant' },
    ['@text.note.comment'] = { fg = colors.nord11, bold = true },
    ['@text.warning'] = { link = 'WarningMsg' },
    ['@text.danger'] = { link = 'ErrorMsg' },
    ['@text.danger.comment'] = { fg = colors.nord0, bg = colors.nord11, bold = true },
    ['@text.diff.add'] = { link = 'diffAdded' },
    ['@text.diff.delete'] = { link = 'diffRemoved' },
    ['@tag'] = { fg = colors.nord9 },
    ['@tag.attribute'] = { fg = colors.nord7 },
    ['@tag.delimiter'] = { fg = colors.nord4 },
    ['@punctuation'] = { link = 'Delimiter' },
    ['@macro'] = { link = 'Macro' },
    ['@structure'] = { link = 'Structure' },
    ['@lsp.type.class'] = { link = '@constructor' },
    ['@lsp.type.comment'] = {},
    ['@lsp.type.decorator'] = { link = '@parameter' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.function'] = { link = '@function' },
    ['@lsp.type.interface'] = { link = '@keyword' },
    ['@lsp.type.macro'] = { link = '@macro' },
    ['@lsp.type.method'] = { link = '@method' },
    ['@lsp.type.namespace'] = { link = '@namespace' },
    ['@lsp.type.parameter'] = { link = '@parameter' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.struct'] = { link = '@constructor' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.typeParameter'] = { link = '@type.definition' },
    ['@lsp.type.variable'] = { link = '@variable' },
  }

  return groups
end

local groups = setcolor()

-- add highlights
for group, settings in pairs(groups) do
  vim.api.nvim_set_hl(0, group, settings)
end
